account/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("",views.account,name="signup_login"),
    path("logout/",auth_views.LogoutView.as_view(),name="logout"),
    path("delete",views.deleteacc,name="deleteacc"),
]

api/urls.py
from rest_framework.routers import DefaultRouter
from .views import TaskAPIs

router = DefaultRouter()
router.register(r'task', TaskAPIs)

urlpatterns = router.urls

core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("",views.publichome,name='publichome'),
    path("home",views.home,name='home'),
    path("addtask",views.addtask,name="addtask"),
    path("mark_done/<int:pk>",views.markdone,name="mark_done"),
    path("delete_task/<int:pk>",views.deletetask,name="delete_task"),
    path("edit_task/<int:pk>",views.edittask,name="edit_task"),
    path("undo_task/<int:pk>",views.undotask,name="undo_task"),
    # path("api/demo/",views.demo_api,name="demo_api"),
]

todolist/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import path
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularSwaggerView,
)
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include('core.urls')),
    path("account/",include('account.urls')),
    path("api/v1/",include('api.urls')),    
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/docs/', SpectacularSwaggerView.as_view(url_name='schema')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api-auth/', include('rest_framework.urls')), 
]

api/models.py
from django.db import models

# Create your models here.

core/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class taskdata(models.Model):
    priority_choice =[
        (1,"HIGH"),
        (2,"MEDIUM"),
        (3,"LOW"),
    ]
    priority = models.IntegerField(choices=priority_choice,default=2)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    task = models.CharField(max_length=250)
    is_completed = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.task

account/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib import messages
from core.models import taskdata
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache

# Create your views here.
def account(request):
    if request.method == 'POST':
        action = request.POST.get('action')

        if action == 'login':
            username = request.POST.get('username')
            password = request.POST.get('password')

            if not User.objects.filter(username=username).exists():
                return render(
                request,
                'signup_login.html',
                {
                    'login_error': 'User not found. Please register first.',
                    'active_tab': 'login'
                }
               )
        
            user = authenticate(request,username=username,password=password)
            if user is not None:
                login(request,user)
                return redirect('home')
            else:
                return render(request,'signup_login.html',{'login_error':'Invalid Password','active_tab': 'login','login_username': username})
        
        if action == 'signup' :
            username = request.POST.get('username')
            email = request.POST.get('email')
            password = request.POST.get('password')
            password1 = request.POST.get('password1')

            if password != password1:
                return render(request,'signup_login.html',{'signup_error':'Password do not match','active_tab': 'signup','signup_username': username,'signup_email': email,})
            if User.objects.filter(username=username):
                return render(request,'signup_login.html',{'signup_error':'User already exists','active_tab': 'signup'})
            if User.objects.filter(email=email):
                return render(request,'signup_login.html',{'signup_error':'Email already used','active_tab': 'signup','signup_username': username,'signup_password': password,'signup_password1': password1})
            user = User.objects.create_user(username=username,email=email,password=password1)
            
            login(request, user)

            return redirect('home')
        
    return render(request,'signup_login.html')

@never_cache
@login_required
def deleteacc(request):
    if request.method == "POST":
        password = request.POST.get("password")
        user = request.user

        if not user.check_password(password):
            messages.error(request, "Incorrect password")
            return redirect("home")

        logout(request)
        user.delete()
        return redirect("publichome")
    return redirect('home')

api/views.py
from django.shortcuts import render
from rest_framework import viewsets
from core.models import taskdata
from core.serializers import TaskSerializers
from rest_framework.permissions import IsAuthenticatedOrReadOnly
# Create your views here.
class TaskAPIs(viewsets.ModelViewSet):
    permission_classes = [IsAuthenticatedOrReadOnly]
    queryset = taskdata.objects.all()
    serializer_class = TaskSerializers


#superuser access tokens :-
#refresh :- eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3MTQzNzY3OCwiaWF0IjoxNzcxMzUxMjc4LCJqdGkiOiJkN2ZkY2I1YjIyMGM0MTExYTE3NzY0Y2U4ZGYxMWRiNCIsInVzZXJfaWQiOiIzIn0.sVGiS5YBG6NXzxgDgDnmshu3AIfPZhfDpwKiQarGAZs
# acees :- eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcxMzUxNTc4LCJpYXQiOjE3NzEzNTEyNzgsImp0aSI6ImMxNzM2ZDU2NWIzNDQ0NjRhN2NhZjM1ZWJkZTYyZWUyIiwidXNlcl9pZCI6IjMifQ.HM9mj8OMsxZb3pDwFxWJ5uTBxJKJ9BoDVOuWfnzaEH8

core/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from .models import taskdata
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache


def publichome(request):
     
     return render(request,'publichome.html')

@never_cache
@login_required(login_url='signup_login')
def home(request):
    if request.user.is_authenticated:
        td = taskdata.objects.filter(user=request.user).order_by('priority','-updated_at')
    else:
        td = taskdata.objects.none() 

    return render(request,'home.html',{'':td,'priority_choices': taskdata.priority_choice,})


def addtask(request):
        if request.method == "POST": 
            data = request.POST["data"]
            priority = request.POST["priority"]
            if data: 
                taskdata.objects.create(user=request.user,task=data,priority=priority)
            else:
                messages.error(request, "Task cannot be empty")
                
            return redirect("home")
        return render(request,"home.html")


def markdone(request, pk):    
        task = get_object_or_404(taskdata, pk=pk)
        task.is_completed = True
        task.save()
        return redirect('home') 


def undotask(request, pk):   
        task = get_object_or_404(taskdata, pk=pk)
        task.is_completed = False
        task.save()
        return redirect('home') 

def deletetask(request, pk):    
        task = get_object_or_404(taskdata, pk=pk)
        task.delete()
        return redirect('home') 
    


def edittask(request, pk):
    task = get_object_or_404(taskdata, pk=pk)

    if request.method == "POST":
        data = request.POST.get('task', '').strip()
        print(data)
        priority = request.POST.get('priority')
        if data:
            task.task = data
            if priority:
                task.priority = priority
            task.save()
            return redirect('home')
        if priority:
             task.priority = priority
             task.save()
             return redirect('home')

    # GET request → open edit page
    return render(request, 'edittask.html', {
        'td': task,
        'priority_choices': taskdata.priority_choice,
    })

# #api test
# @api_view(["GET"])
# def demo_api(request):
#      return Response({
#           "message":"Naya World",
#           "status":"success"
#      })
     
     

templates/edittask.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Task - Django TODO App</title>

    <!-- Bootstrap -->
    <link rel="icon" type="image/x-icon" href="{% static 'favicon-bl-dk.ico' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
      <a href="{% url 'home' %}"
   class="btn btn-outline-success position-fixed"
   style="top: 16px; right: 16px; z-index: 1050;">
     ← Back
 </a>
    <div class="container">
        <h3 class="pt-5 pb-5 text-center">Django TODO App - Edit Task</h3>
        <form action="{% url 'edit_task' td.pk %}" method="POST" style="max-width: 500px; margin: auto;">
            {% csrf_token %}
            <div class="form-group row g-1">
                <div class="col-12 col-md-8">
                     <div class="input-group">
                        <textarea name="task" class="form-control" rows="2" style="resize: none;">{{ td.task }}</textarea>
                        <span class="input-group-text p-0 px-2">
                            <span class="badge 
                                {% if td.priority == 1 %}bg-danger
                                {% elif td.priority == 2 %}bg-warning text-dark
                                {% else %}bg-success{% endif %}">
                                {{ td.get_priority_display }}
                            </span>
                        </span>
                    </div>
                </div>
            <div class="col-12 col-md-3">
                <select name="priority" class="form-select py-md-3 py-1">
                    {% for value, label in priority_choices %}
                        <option value="{{ value }}"
                            {% if value == td.priority %}selected{% endif %}>
                            {{ label }}
                        </option>
                    {% endfor %}
                </select>
            </div>
                <div class="col-12 col-md-4">
                    <button type="submit" class="btn btn-primary w-100">
                        <i class="fa fa-plus"></i> Update
                    </button>
                </div>
            </div>
        </form>
    </div>
<footer class="bg-light text-center py-3 mt-4 border-top">
    <small>
        © {% now "Y" %} CodeCrafter-droid. All rights reserved. |
    <a href="https://github.com/CodeCrafter-droid" target="_blank">
        GitHub
    </a>
    </small>
</footer>
</body>
</html>

templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TODO LIST - Home</title>

    <!-- Bootstrap -->
     <link rel="icon" type="image/x-icon" href="{% static 'favicon-bl-dk.ico' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
    <style>
        .form-control{
        padding: 1.375rem .75rem !important;
    }
    </style>
</head>
<body>
<!-- {% if messages %}
<div class="toast-container position-fixed top-0 end-0 p-3" style="z-index: 1055;">
    {% for message in messages %}
        <div class="toast show bg-danger text-white">
            <div class="toast-body">
                {{ message }}
            </div>
        </div>
    {% endfor %}
</div>
{% endif %} -->
    <nav class="navbar navbar-light bg-light px-3">
    <div class="container-fluid">
        <!-- Left -->
        <div class="col-4 text-start">
        <a class="navbar-brand fw-bold" href="#">TODO</a>
        {% if user.is_superuser %}
            <span class="d-block d-md-inline me-md-2 mb-1 mb-md-0 fw-semibold">
            <form action="{% url 'admin:index' %}" method="get" style="display:inline;">
            <button type="submit" class="btn btn-primary btn-sm">
                <i class="bi bi-person-fill-gear"></i>
            </button>
        </form>
        </span>
        {% endif %}
        </div>

        <!-- Center -->
        <div class="col-4 text-center">
        <span class="h3 mb-0">Django ToDo App</span>
        </div>
    <div class="col-4 text-end">
            <span class="d-block d-md-inline me-md-2 mb-1 mb-md-0 fw-semibold">
                Hello, {{ request.user.username }}
            </span>
        <form method="post" action="{% url 'logout' %}" class="d-block d-md-inline me-1 mb-1 mb-md-0">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">
                Log out
            </button>
        </form>
            <form method="post" action="{% url 'deleteacc' %}" class="d-block d-md-inline">
            {% csrf_token %}
                <button  type="button"  class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteAccountModal">
                Delete Account
                </button>
            </form>
    </div>
</nav>    
<div class="container">
        <div class="row">
            <h4>My Day</h4>
            <p class="text-muted">{% now "jS F Y" %}</p>
            <div class="col-md-7 col-lg-7" style="height: 450px; overflow: scroll;">
                <!-- List of all the tasks for the day -->
                {% for task in td %}
                {% if task.is_completed == False %}
                <div class="card m-1">
                    <div class="card-body">
                        {{ task.task }}
                        <span style="position: relative; float: right;">
                                <span class="badge 
                                    {% if task.priority == 1 %}bg-danger
                                    {% elif task.priority == 2 %}bg-warning text-dark
                                    {% else %}bg-success{% endif %}">
                                    {{ task.get_priority_display }}
                                </span>
                            <form action="{% url 'mark_done' task.id %}" style="display:inline;">
                                <button type="submit" class="btn btn-success btn-sm">
                                        <i class="fa fa-check"></i> Mark as Done
                                </button>
                            </form>
                            <form action="{% url 'delete_task' task.id %}" style="display:inline;" onsubmit="return confirm('Are you sure you want to delete this task?');">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger btn-sm">
                                    <i class="fa fa-trash"></i>
                                </button>
                            </form>
                            <form action="{% url 'edit_task' task.id %}" method="get" style="display:inline;">
                                <button type="submit" class="btn btn-primary btn-sm">
                                    <i class="fa fa-pencil"></i>
                                </button>
                           </form>
                        </span>
                    </div>
                </div>
               {% endif %}
               {% endfor %}
            </div>
            <div class="col-md-5 col-lg-5" style="height: 450px; overflow: scroll;">
                <h5>Completed Tasks</h5>
                <!-- List of all the tasks that have completed -->
                {% for task in td %}
                {% if task.is_completed  %}
                <div class="card m-1">
                    <div class="card-body">
                        {{task.task}}
                        <span style="position: relative; float: right;">
                          <form action="{% url 'undo_task' task.id %}" style="display:inline;">
                                <button type="submit" class="btn btn-warning btn-sm">
                                    <i class="fa fa-undo"></i> Undo
                                </button>
                          </form>
                            <form action="{% url 'delete_task' task.id %}" style="display:inline;">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger btn-sm">
                                    <i class="fa fa-trash"></i>
                                </button>
                            </form>
                        </span>
                    </div>
                </div>
                {% endif %}
                {% endfor %}
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 col-lg-6 p-0 mt-2">
                <!-- To Do Form -->
                <form action="{% url 'addtask' %}" method="post" class="mx-auto px-2" style="max-width: 500px;">
                    {% csrf_token %}
                        <select name="priority" class="form-select">
                            {% for value, label in priority_choices %}
                                <option value="{{ value }}"
                                    {% if value == 2 %}selected{% endif %}>
                                    {{ label }}
                                </option>
                            {% endfor %}
                        </select>
                    <div class="row g-2">
                        <div class="col-12 col-md-8">
                            <input type="text" class="form-control" placeholder="Add a task" name="data" required>
                        </div>
                        <div class="col-12 col-md-4">
                            <button type="submit" class="btn btn-primary w-100 h-100">
                                <i class="fa fa-plus"></i> Add
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="modal fade" id="deleteAccountModal" tabindex="-1" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">

                <div class="modal-header bg-danger text-white">
                  <h5 class="modal-title">⚠ Delete Account</h5>
                  <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                </div>

                <form method="post" action="{% url 'deleteacc' %}">
                      {% csrf_token %}              
                    <div class="modal-body">
                        {% if messages %}
                        {% for message in messages %}
                          <div class="alert alert-danger py-2">
                            {{ message }}
                          </div>
                        {% endfor %}
                        {% endif %}
                            <p class="fw-bold text-danger">
                              This action is permanent and cannot be undone.
                            </p>
                            <p>Please enter your password to confirm:</p>
                        <div class="position-relative">
                            <input  type="password" id="loginPassword" name="password" class="form-control pe-5" placeholder="Enter your password" required>
                            <span  class="position-absolute top-50 end-0 translate-middle-y me-3" style="cursor: pointer;" onclick="togglePassword('loginPassword', this)">
                                <i class="fa fa-eye"></i>
                            </span>
                        </div>
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
                              Cancel
                            </button>
                  
                            <button type="submit" class="btn btn-danger">
                              Yes, Delete My Account
                        </button>
                    </div>
                </form>

            </div>
        </div>
    </div>
<script>
  function togglePassword(inputId, iconSpan) {
    const input = document.getElementById(inputId);
    const icon = iconSpan.querySelector("i");

    if (input.type === "password") {
      input.type = "text";
      icon.classList.remove("fa-eye");
      icon.classList.add("fa-eye-slash");
    } else {
      input.type = "password";
      icon.classList.remove("fa-eye-slash");
      icon.classList.add("fa-eye");
    }
  }
</script>
{% if messages %}
<script>
  const deleteModal = new bootstrap.Modal(
    document.getElementById('deleteAccountModal')
  );
  deleteModal.show();
</script>
{% endif %}
<footer class="bg-light text-center py-3 mt-4 border-top">
    <small>
        © 2026 CodeCrafter-droid. All rights reserved. |
    <a href="https://github.com/CodeCrafter-droid" target="_blank">
        GitHub
    </a>
    </small>
</footer>
</body>
</html>

templates/publichome.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TODO LIST - Home</title>

    <!-- Bootstrap -->
     <link rel="icon" type="image/x-icon" href="{% static 'favicon-bl-dk.ico' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    
    <style>
        .form-control{
        padding: 1.375rem .75rem !important;
    }
    </style>
</head>
<body>
    <nav class="navbar navbar-light bg-light px-3">
  <div class="container-fluid">

    <!-- Left -->
    <div class="col-4">
      <a class="navbar-brand fw-bold" href="#">TODO</a>
    </div>

    <!-- Center -->
    <div class="col-4 text-center">
      <span class="h3 mb-0">Django ToDo App</span>
    </div>
    <div class="col-4 text-end">
        <a href="{% url 'signup_login' %}?tab=login" class="btn btn-outline-primary me-1">
            Login
        </a>
        <a href="{% url 'signup_login'%}?tab=signup" class="btn btn-primary">
            Sign Up
        </a>
    </div>
</nav> 
<div class="d-flex justify-content-center align-items-center" style="height: calc(100vh - 56px);">
  <div class="text-center" style="max-width: 400px;">
    <h4>What you can do:</h4>
    <ul class="list-group mt-3">
      <li class="list-group-item"> 
        <a href="{% url 'signup_login' %}?tab=sigup" class="text-decoration-none">
          ✅ Add tasks
        </a>
      </li>
      <li class="list-group-item">
        <a href="{% url 'signup_login' %}?tab=sigup" class="text-decoration-none">
          🕒 Mark Done
        </a>
      </li>
      <li class="list-group-item">
        <a href="{% url 'signup_login' %}?tab=sigup" class="text-decoration-none">
          ⭐ Mark as complete
        </a>
      </li>
    </ul>
  </div>
</div> 
<footer class="bg-light text-center py-3 mt-4 border-top">
    <small>
        © {% now "Y" %} CodeCrafter-droid. All rights reserved. |
    <a href="https://github.com/CodeCrafter-droid" target="_blank">
        GitHub
    </a>
    </small>
</footer>
</body>